name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build Successful"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Test Successful"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deployment Successful"
