name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Stage
        run: echo "Build Successful"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test Stage
        run: echo "Test Successful"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy Stage
        run: echo "Deployment Successful"